# Generated by Django 4.1.7 on 2023-03-23 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcelas',
            options={'verbose_name_plural': 'Parcelas'},
        ),
    ]
